name: Bot
on:
  workflow_dispatch:
    inputs:
      telegram:
        required: true
        description: 'Base64-encoded JSON payload from gotd/bot'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        uses: actions/github-script@v5
        with:
          script: |
            const { inputs } = context.payload
            const telegram = JSON.parse(Buffer.from(inputs.telegram, 'base64').toString('utf-8'))
            console.log(JSON.stringify(telegram))
